default: &default
  adapter: postgresql
  encoding: utf8
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fakebook_postgresql_dev

test:
  <<: *default
  database: fakebook_postgresql_test