# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be4328b6e83a75d73875f844c670c7ed71863050fcfeeb22a4a4ea41d27864b1b86948d132af9ecd1614507617515b12cdff7f06a250afa4b1114916820429ea

test:
  secret_key_base: 779ed6b93a32a6f4af042b28725e6992bc9921500b2ae00e8288ec436450742d3d3dbfae5f2bd308e2b49f1b19379d62d8249b4303c6f1d2132daa13f86dbe20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
