# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8d4642623e6365ec028b8794e51aff8834685d9ce96c9dc91e21bbdbc449a291fd3efa5b065a5981bd1692ebee2a17ffaf0d7cf696471b7c0e311a48f6e7667

test:
  secret_key_base: b7fcaea5c520e9ba36068bdeab41bb1897c8399dfc7db68fda1b5ea45c4bd57d69197c991ec18145e55bf531a493474b9c0363aed3d3b62e0f421f4636dbe50d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
